### ISSUE TITLE
Not Compatible with Vaadin 8.1.3

### ISSUE THREAD

**Issue by wilsontjohnson** [bonprix/vaadin-excel-exporter#28]
Crash when exporting in Vaadin 8.1.3.

`Caused by: java.lang.NoSuchMethodError: com.vaadin.ui.Grid$Column.getValueProvider()Lcom/vaadin/server/SerializableFunction;
	at org.vaadin.addons.excelexporter.ExportToExcel.addGridDataRow(ExportToExcel.java:399)`

Suggested fix:
Change versions In the pom.xml for the build.

Vaadin 8.1 changed the getValueProvider method to return a ValueProvider.
It is still a implementation of SerializableFunction and by extension Function, so no code change is needed, just a rebuild for Vaadin 8.1

**Comment by rahulearl** [comment]
Hi,

I am using Vaadin Spring Boot Starter. Below is my gradle dependency:

`compile("com.vaadin:vaadin-spring-boot-starter")`

I still get this error. I even updated the dependency to 
`compile("com.vaadin:vaadin-spring-boot-starter:2.0-SNAPSHOT")`
but still getting the same error.

I am a newbie. Please let me get out of this exception.
Thanks,

**Comment by yeonjoonam** [comment]
I ran this add-on with Vaadin 8.1.0 and got the same issue 
"Caused by: java.lang.NoSuchMethodError: com.vaadin.ui.Grid$Column.getValueProvider()Lcom/vaadin/server/SerializableFunction; at org.vaadin.addons.excelexporter.ExportToExcel.addGridDataRow(ExportToExcel.java:399)"

For now, I went back to Vaadin 8.0.6 as Wilson suggested as above.
I am wondering when "Export To Excel" add-on will support Vaadin 8.1.0 and higher?

**Comment by ScottHuangZL** [comment]
2 tentative solutions:

1. You can change to 8.0.6 in POM to tentative fix the issue.    (To meet the addon Vaadin version)

2. Or, you can download https://github.com/bonprix/vaadin-excel-exporter to your local machine.
    a. Change that project Vaadin version in POM from 8.0.6 to 8.1.5 and then recompile it (mvn clean; mvn install)
        It should be generate 2.1-SNAPSHOT version in your local.
    b. Go to your personal project, change Vaadin version to 8.1.5 
        and <vaadin-excel-exporter.version>2.1-SNAPSHOT</vaadin-excel-exporter.version>
   
    Then your project able use the latest local build vaadin-excel-exporter.

Myself use #2 to tentative resolve the issue.
